# Generated by Django 2.2.1 on 2019-06-02 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(default=33074170350000)),
                ('slug', models.SlugField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.IntegerField(default=12345)),
                ('taxing_body_count', models.IntegerField()),
                ('tax_year', models.DateTimeField(verbose_name='year published')),
                ('slug', models.SlugField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='propaddress',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctaxes.TaxCode'),
        ),
    ]
