# Generated by Django 2.2.1 on 2019-06-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0002_auto_20190601_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcode',
            name='tax_year',
        ),
    ]
