# Generated by Django 2.2.1 on 2019-06-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0003_remove_taxcode_tax_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(default=2017)),
                ('assessment_district', models.CharField(default='Barrington', max_length=50)),
                ('assessment_ratio', models.IntegerField(default=0)),
                ('equalization_factor', models.IntegerField(default=2.0)),
            ],
        ),
        migrations.AddField(
            model_name='taxcode',
            name='agency',
            field=models.IntegerField(default=10010000),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='agency_name',
            field=models.CharField(default='COUNTY OF COOK', max_length=50),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='agency_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='assessment_district',
            field=models.CharField(default='Barrington', max_length=50),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='tax_code_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='tax_year',
            field=models.IntegerField(default=2017),
        ),
        migrations.AlterField(
            model_name='propaddress',
            name='slug',
            field=models.SlugField(max_length=14),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='slug',
            field=models.SlugField(max_length=5),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='taxing_body_count',
            field=models.IntegerField(default=0),
        ),
    ]
