# Generated by Django 2.2.1 on 2019-06-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0004_auto_20190602_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentRatio',
        ),
        migrations.AddField(
            model_name='taxcode',
            name='equalization_factor',
            field=models.DecimalField(decimal_places=3, default=2.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='propaddress',
            name='tax_code',
            field=models.IntegerField(default=12345),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='agency_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='slug',
            field=models.SlugField(max_length=10),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='tax_code_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
