# Generated by Django 2.2.1 on 2019-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0005_auto_20190602_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propaddress',
            name='slug',
        ),
        migrations.AlterField(
            model_name='propaddress',
            name='pin',
            field=models.CharField(default=33074170350000, max_length=14),
        ),
        migrations.AlterField(
            model_name='propaddress',
            name='tax_code',
            field=models.CharField(default=12345, max_length=6),
        ),
    ]
